In [4]:
import numpy as np

In [5]:
mt = np.array([1, 3, 4], dtype = np.float64)

print(mt)
vazio = np.zeros([3,3])
print(vazio)

[1. 3. 4.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
um = np.ones([4, 5])
print(um)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
ale = np.random.random((5))
print(ale)

[0.44283006 0.08144699 0.65349353 0.83304453 0.41947558]


In [9]:
normal = np.random.randn((3))
print(normal)

[ 1.76362577 -0.14626989 -0.09348464]


In [10]:
matrizrand = np.random.random([3,4])
print(matrizrand)

[[0.57798229 0.07587623 0.1135791  0.3313314 ]
 [0.34856765 0.91346008 0.06632739 0.64908541]
 [0.30171823 0.78334578 0.80909317 0.75124304]]


In [11]:
matrizint = np.random.randint([3,4])
print(matrizint)

[0 0]


Geração com semente

In [12]:
gnr = np.random.default_rng(1)
ale9 = gnr.random(2)

print(ale9)

print(10*"-")

ale90 = gnr.integers(11, size=(8,8))
print(ale90)

[0.51182162 0.9504637 ]
----------
[[ 0  1  9 10  2  3  9  4]
 [ 3  9  2  4  7  6  0  0]
 [ 9  8  9  5  8  3  4  8]
 [ 1  3  1  4 10  1  4  4]
 [ 9  2  5  2  0  8  0  3]
 [ 5  5  1 10  8 10  1  7]
 [ 3  5 10  3  7  1  3 10]
 [ 4  5  3  1  4  6  5  8]]


In [13]:
#UNIQUE
j = np.array([1,2,3,4,5,6,7,7,7,77,7,8,8,9,2,3,0,10,10,10])
j = np.unique(j)

print(j)


[ 0  1  2  3  4  5  6  7  8  9 10 77]


In [14]:
matriza = np.array([[1,2,3,4,5],[1,3,4,5,6],[1,3,4,5,6]])
print(matriza)

print(10*'-')

print(matriza[0][1])

print(10*'-')

print(matriza.shape)

[[1 2 3 4 5]
 [1 3 4 5 6]
 [1 3 4 5 6]]
----------
2
----------
(3, 5)


Funções matematicas numa matriz

In [15]:
print(matriza.max())
print(10*'-')
print(matriza.min())
print(10*'-')
print(matriza.sum())
print(10*'-')
print(matriza.mean())
print(10*'-')
print(matriza.std())

6
----------
1
----------
53
----------
3.533333333333333
----------
1.6679994670929073


raiz quadrada e exp

In [16]:
print(np.sqrt(matriza))
print(10*'-')
print(np.exp(matriza))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [1.         1.73205081 2.         2.23606798 2.44948974]
 [1.         1.73205081 2.         2.23606798 2.44948974]]
----------
[[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
 [  2.71828183  20.08553692  54.59815003 148.4131591  403.42879349]
 [  2.71828183  20.08553692  54.59815003 148.4131591  403.42879349]]


Extração de dados

In [17]:
array = np.array([1, 4, 5, 6, 7, 8, 10, 11])
print(array[1])
print(10*'-')
print(array[0:2])
print(10*'-')
print(array[1:])
print(10*'-')
print(array[-3:])

4
----------
[1 4]
----------
[ 4  5  6  7  8 10 11]
----------
[ 8 10 11]


In [18]:
vetor = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(vetor)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
primeiralinha = vetor [0, :]
print(primeiralinha)
print(10*".")
segundalinha = vetor [1, :]
print(segundalinha)
print(10*".")
terceiralinha = vetor[2, :]
print(terceiralinha)

[1 2 3]
..........
[4 5 6]
..........
[7 8 9]


In [27]:
primeiracoluna = vetor[:, 0] 
print(primeiracoluna)
print(10*".")
segundacoluna = vetor[:, 1]
print(segundacoluna)
print(10*".")
terceiracoluna = vetor[: , 2]
print(terceiracoluna)

[1 4 7]
..........
[2 5 8]
..........
[3 6 9]


adição e multiplicação de matrizes

In [31]:
n = np.array([[1,2,3,4], [1,2,3,4]])
p = np.array([[5,6,7,8],[5,6,7,8]])

resultado = n+p
print(resultado)
print(10*".")

resultado2 = n*p
print(resultado2)
print(10*".")

q = [[1,2,3,4], [1,2,3,4,5]]
t = [[3,4,7]]

resultado3 = q+t

print(resultado3)
print(10*".")

[[ 6  8 10 12]
 [ 6  8 10 12]]
..........
[[ 5 12 21 32]
 [ 5 12 21 32]]
..........
[[1, 2, 3, 4], [1, 2, 3, 4, 5], [3, 4, 7]]
..........


arranjo e transposição

In [37]:
op = np.arange(15).reshape((3,5))
print(op)

print(10*".")

opt = op.T

print(opt)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
..........
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


expressões logicas

In [42]:
expl = np.random.randn(4,4)
print(expl)
print(10*".")
x = expl > 0
print(x)
y = np.where(expl>0, "sim", "não")
print(10*".")
print(y)

[[ 0.93557623  0.54288805  0.20962007 -1.07588478]
 [-0.22312723  2.02979885 -0.74961518  1.98881822]
 [ 0.1262033  -0.06292946  1.10805155 -0.16442539]
 [ 0.28133698  0.18110129 -0.39683275 -0.15406998]]
..........
[[ True  True  True False]
 [False  True False  True]
 [ True False  True False]
 [ True  True False False]]
..........
[['sim' 'sim' 'sim' 'não']
 ['não' 'sim' 'não' 'sim']
 ['sim' 'não' 'sim' 'não']
 ['sim' 'sim' 'não' 'não']]
