In [4]:
import numpy as np

In [5]:
mt = np.array([1, 3, 4], dtype = np.float64)

print(mt)
vazio = np.zeros([3,3])
print(vazio)

[1. 3. 4.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
um = np.ones([4, 5])
print(um)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
ale = np.random.random((5))
print(ale)

[0.41812084 0.96778025 0.01042469 0.26798099 0.23245212]


In [9]:
normal = np.random.randn((3))
print(normal)

[-0.24428662  0.21585113 -0.0902327 ]


In [10]:
matrizrand = np.random.random([3,4])
print(matrizrand)

[[0.44461704 0.88068846 0.52937815 0.80857748]
 [0.37829364 0.61213273 0.25996471 0.85564951]
 [0.35916689 0.14283811 0.46021312 0.06558982]]


In [11]:
matrizint = np.random.randint([3,4])
print(matrizint)

[2 3]


Geração com semente

In [23]:
gnr = np.random.default_rng(1)
ale9 = gnr.random(2)

print(ale9)

print(10*"-")

ale90 = gnr.integers(11, size=(8,8))
print(ale90)

[0.51182162 0.9504637 ]
----------
[[ 0  1  9 10  2  3  9  4]
 [ 3  9  2  4  7  6  0  0]
 [ 9  8  9  5  8  3  4  8]
 [ 1  3  1  4 10  1  4  4]
 [ 9  2  5  2  0  8  0  3]
 [ 5  5  1 10  8 10  1  7]
 [ 3  5 10  3  7  1  3 10]
 [ 4  5  3  1  4  6  5  8]]


In [24]:
#UNIQUE
j = np.array([1,2,3,4,5,6,7,7,7,77,7,8,8,9,2,3,0,10,10,10])
j = np.unique(j)

print(j)


[ 0  1  2  3  4  5  6  7  8  9 10 77]


In [27]:
matriza = np.array([[1,2,3,4,5],[1,3,4,5,6],[1,3,4,5,6]])
print(matriza)

print(10*'-')

print(matriza[0][1])

print(10*'-')

print(matriza.shape)

[[1 2 3 4 5]
 [1 3 4 5 6]
 [1 3 4 5 6]]
----------
2
----------
(3, 5)


Funções matematicas numa matriz

In [33]:
print(matriza.max())
print(10*'-')
print(matriza.min())
print(10*'-')
print(matriza.sum())
print(10*'-')
print(matriza.mean())
print(10*'-')
print(matriza.std())

6
----------
1
----------
53
----------
3.533333333333333
----------
1.6679994670929073


raiz quadrada e exp

In [34]:
print(np.sqrt(matriza))
print(10*'-')
print(np.exp(matriza))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [1.         1.73205081 2.         2.23606798 2.44948974]
 [1.         1.73205081 2.         2.23606798 2.44948974]]
----------
[[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
 [  2.71828183  20.08553692  54.59815003 148.4131591  403.42879349]
 [  2.71828183  20.08553692  54.59815003 148.4131591  403.42879349]]


Extração de dados

In [38]:
array = np.array([1, 4, 5, 6, 7, 8, 10, 11])
print(array[1])
print(10*'-')
print(array[0:2])
print(10*'-')
print(array[1:])
print(10*'-')
print(array[-3:])

4
----------
[1 4]
----------
[ 4  5  6  7  8 10 11]
----------
[ 8 10 11]
